site_name: "SRE DOCUMENTATION PAGE"
# Project Information
site_url: 'https://pages.github.ibm.com/sashtiachuthank/sre_s5_docs/' 
site_author: Sashti Achuthan K

# Repository Information
repo_name: 'sashtiachuthank/sre_s5_docs'
repo_url: 'https://github.ibm.com/sashtiachuthank/sre_s5_docs'
docs_dir: 'docs'
site_dir: 'site'
remote_branch: 'gh-pages'
remote_name: 'origin'

#  - pymdownx.tilde
#extra_css:
#  - "stylesheets/extra_css.css"
#extra_javascript:
#  - javascripts/extra.js
