

    - name: Grep the filesystem which is above the threshold limit 
      shell: df -h | awk 'NR==1 || $5+0 > 80' 
      register: diskspacelinux
      
    - name: Notify via email
      mail:
        host: "na.relay.ibm.com"
        from: "diskspace_@ds_c"
        to: "{{ email_address }}"
        subject: "Filesystems above threshold limit"
        body: |
          <html>
            <body>
              <p style="color: red; font-weight: bold;"> Filesystems above threshold limit in {{ inventory_hostname }} </p>
               <pre>{{ diskspacelinux.stdout_lines | to_nice_json }}</pre>
            </body>
          </html>
        subtype: html
      ignore_errors: true
