---
- name: Main Playbook
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Linux
      include_role:
        name: passwdlinux
      when: activity_type == 'linuxpasswdreset'

    - name: AIX
      include_role:
        name: passwdaix
      when: activity_type == 'aixpasswdreset'

    - name: WINDOWS
      include_role:
        name: windows
      when: activity_type == 'windowspasswdreset'
