  - name: Query the TSM Client Scheduler service
    win_service:
      name: "TSM Client Scheduler"
    register: tsm_service_status
  - name: Display the service state
    debug:
      msg: "The TSM Client Scheduler service is {{ tsm_service_status.state }}"

  - name: Start the TSM Client Scheduler service if not running
    win_service:
      name: "TSM Client Scheduler"
      state: started
    when: tsm_service_status.state != 'running'
    register: start_service
  - name: Display start service result
    debug:
      msg: "TSM Service started successfully: {{ start_service.state }}"
    when: tsm_service_status.state != 'running'